/**
 * SRI LAKSHMI BAKERY - Expanded Products Catalog (60+ Products)
 * Categories: Cakes, Bakery, Cool Drinks, Pastries, Cookies, Snacks
 */

window.BakeryProducts = (function () {
  const products = [
    // ==========================================
    // CAKES CATALOG (20+ Products)
    // ==========================================
    {
      id: "cake-001",
      name: "Royal Rasmalai Fusion Cake",
      category: "cakes",
      subCategory: "Birthday Cakes",
      price: 599,
      unit: "0.5 kg",
      isCake: true,
      description: "Cardamom sponge infused with saffron milk, topped with soft rasmalai & pistachios.",
      fullDesc: "An authentic Indian celebration favorite! Fluffy sponge soaked in aromatic saffron-cardamom milk, layered with soft rasmalai pieces, crushed pistachios, and edible rose petals.",
      image: "https://images.unsplash.com/photo-1535141192574-5d4897c13136?auto=format&fit=crop&w=800&q=80",
      ingredients: ["Fresh Rasmalai", "Saffron Milk", "Cardamom Sponge", "Pistachio Curls"],
      bestseller: true,
      rating: 4.9,
      reviewsCount: 180,
      tags: ["birthday", "rasmalai", "indian", "fusion"],
      available: true
    },
    {
      id: "cake-002",
      name: "Butterscotch Crunch Cake",
      category: "cakes",
      subCategory: "Birthday Cakes",
      price: 450,
      unit: "0.5 kg",
      isCake: true,
      description: "Rich caramel sponge layered with crunchy butterscotch praline and whipped cream.",
      fullDesc: "Golden vanilla sponge smothered in creamy caramel butterscotch sauce, filled with crunchy praline bits and topped with chocolate crown decorations.",
      image: "https://images.unsplash.com/photo-1578985545062-69928b1d9587?auto=format&fit=crop&w=800&q=80",
      ingredients: ["Caramel Praline", "Butterscotch Sauce", "Vanilla Sponge", "Whipped Cream"],
      bestseller: true,
      rating: 4.8,
      reviewsCount: 155,
      tags: ["butterscotch", "caramel", "crunch"],
      available: true
    },
    {
      id: "cake-003",
      name: "Fresh Pineapple Delight Cake",
      category: "cakes",
      subCategory: "Fruit Cakes",
      price: 420,
      unit: "0.5 kg",
      isCake: true,
      description: "Moist sponge layered with real pineapple slices, maraschino cherries and light cream.",
      fullDesc: "Soft vanilla cake filled with juicy pineapple chunks, sweet pineapple glaze, and topped with glace cherries and white chocolate flakes.",
      image: "https://images.unsplash.com/photo-1565958011703-44f9829ba187?auto=format&fit=crop&w=800&q=80",
      ingredients: ["Fresh Pineapple Slices", "Vanilla Sponge", "Whipped Cream", "Glace Cherries"],
      bestseller: false,
      rating: 4.7,
      reviewsCount: 112,
      tags: ["pineapple", "fruit", "fresh"],
      available: true
    },
    {
      id: "cake-004",
      name: "Red Velvet Heart Celebration Cake",
      category: "cakes",
      subCategory: "Anniversary Cakes",
      price: 520,
      unit: "0.5 kg",
      isCake: true,
      description: "Vibrant red cocoa sponge layered with silky cream cheese frosting.",
      fullDesc: "Heart-shaped red velvet sponge layered with authentic tangy cream cheese frosting and fine velvet crumbs.",
      image: "https://images.unsplash.com/photo-1586985289688-ca3cf47d3e6e?auto=format&fit=crop&w=800&q=80",
      ingredients: ["Red Cocoa Sponge", "Cream Cheese Frosting", "Vanilla Extract"],
      bestseller: true,
      rating: 4.9,
      reviewsCount: 168,
      tags: ["red velvet", "anniversary", "heart"],
      available: true
    },
    {
      id: "cake-005",
      name: "Belgian Chocolate Fudge Cake",
      category: "cakes",
      subCategory: "Chocolate Cakes",
      price: 499,
      unit: "0.5 kg",
      isCake: true,
      description: "Rich 3-layer dark chocolate fudge cake with fresh cream ganache.",
      fullDesc: "Handcrafted with imported 70% Belgian dark chocolate, moist cocoa sponge layers, and silky chocolate buttercream.",
      image: "https://images.unsplash.com/photo-1578985545062-69928b1d9587?auto=format&fit=crop&w=800&q=80",
      ingredients: ["Belgian Dark Chocolate", "Organic Flour", "Pure Butter"],
      bestseller: true,
      rating: 4.9,
      reviewsCount: 210,
      tags: ["chocolate", "fudge", "belgian"],
      available: true
    },
    {
      id: "cake-006",
      name: "Black Forest Celebration Cake",
      category: "cakes",
      subCategory: "Black Forest",
      price: 480,
      unit: "0.5 kg",
      isCake: true,
      description: "Classic German chocolate sponge layered with whipped vanilla cream and cherries.",
      fullDesc: "Traditional cocoa sponge soaked in cherry syrup, filled with double cream and topped with maraschino cherries.",
      image: "https://images.unsplash.com/photo-1606313564200-e75d5e30476c?auto=format&fit=crop&w=800&q=80",
      ingredients: ["Cocoa Sponge", "Whipped Cream", "Maraschino Cherries"],
      bestseller: true,
      rating: 4.8,
      reviewsCount: 140,
      tags: ["black forest", "cherries", "classic"],
      available: true
    },
    {
      id: "cake-007",
      name: "White Forest Snow Cake",
      category: "cakes",
      subCategory: "White Forest",
      price: 460,
      unit: "0.5 kg",
      isCake: true,
      description: "Vanilla sponge with white chocolate curls, cherries and mascarpone cream.",
      fullDesc: "Delicate white vanilla cake coated in fluffy whipped cream, covered with fine white chocolate shavings.",
      image: "https://images.unsplash.com/photo-1519869325930-281384150729?auto=format&fit=crop&w=800&q=80",
      ingredients: ["Vanilla Sponge", "White Chocolate Curls", "Cherries"],
      bestseller: false,
      rating: 4.7,
      reviewsCount: 95,
      tags: ["white forest", "vanilla", "snow"],
      available: true
    },
    {
      id: "cake-008",
      name: "Madagascar Vanilla Bean Cake",
      category: "cakes",
      subCategory: "Vanilla",
      price: 399,
      unit: "0.5 kg",
      isCake: true,
      description: "Classic golden vanilla sponge infused with organic vanilla bean seeds.",
      fullDesc: "Timeless golden cake made with pure Madagascar vanilla extract and light butter glaze.",
      image: "https://images.unsplash.com/photo-1535141192574-5d4897c13136?auto=format&fit=crop&w=800&q=80",
      ingredients: ["Madagascar Vanilla", "Pure Butter", "Wheat Flour"],
      bestseller: false,
      rating: 4.6,
      reviewsCount: 88,
      tags: ["vanilla", "classic"],
      available: true
    },
    {
      id: "cake-009",
      name: "Fresh Alphonso Mango Cream Cake",
      category: "cakes",
      subCategory: "Fruit Cakes",
      price: 549,
      unit: "0.5 kg",
      isCake: true,
      description: "Seasonal vanilla cake filled with fresh Alphonso mango pulp and cream.",
      fullDesc: "Specialty summer cake prepared with fresh Ratnagiri Alphonso mango puree and light cream glaze.",
      image: "https://images.unsplash.com/photo-1535141192574-5d4897c13136?auto=format&fit=crop&w=800&q=80",
      ingredients: ["Alphonso Mango", "Vanilla Sponge", "Cream Glaze"],
      bestseller: true,
      rating: 4.9,
      reviewsCount: 130,
      tags: ["mango", "alphonso", "seasonal"],
      available: true
    },
    {
      id: "cake-010",
      name: "Strawberry Mousse Velvet Cake",
      category: "cakes",
      subCategory: "Fruit Cakes",
      price: 499,
      unit: "0.5 kg",
      isCake: true,
      description: "Layered sponge with fresh Mahabaleshwar strawberry puree and mousse.",
      fullDesc: "Fruity and elegant cake layered with natural strawberry reduction and light berry cream.",
      image: "https://images.unsplash.com/photo-1587314168485-3236d6710814?auto=format&fit=crop&w=800&q=80",
      ingredients: ["Fresh Strawberries", "Whipped Mousse", "Vanilla Sponge"],
      bestseller: false,
      rating: 4.8,
      reviewsCount: 92,
      tags: ["strawberry", "berry", "mousse"],
      available: true
    },
    {
      id: "cake-011",
      name: "Tiramisu Espresso Coffee Cake",
      category: "cakes",
      subCategory: "Specialty Cakes",
      price: 550,
      unit: "0.5 kg",
      isCake: true,
      description: "Italian coffee-soaked cake layered with mascarpone cream and cocoa powder.",
      fullDesc: "Rich espresso-soaked sponge layered with whipped mascarpone cheese and dusted with Dutch cocoa.",
      image: "https://images.unsplash.com/photo-1578985545062-69928b1d9587?auto=format&fit=crop&w=800&q=80",
      ingredients: ["Espresso Coffee", "Mascarpone Cheese", "Dutch Cocoa"],
      bestseller: false,
      rating: 4.8,
      reviewsCount: 75,
      tags: ["tiramisu", "coffee", "espresso"],
      available: true
    },
    {
      id: "cake-012",
      name: "Customized Edible Photo Cake",
      category: "cakes",
      subCategory: "Photo Cakes",
      price: 650,
      unit: "1.0 kg",
      isCake: true,
      description: "Personalized birthday cake featuring your custom printed edible photograph.",
      fullDesc: "Upload your favorite family or birthday photo to print on an edible sugar icing sheet over your choice of cake flavour.",
      image: "https://images.unsplash.com/photo-1535141192574-5d4897c13136?auto=format&fit=crop&w=800&q=80",
      ingredients: ["Sugar Icing Sheet", "Custom Flavour Sponge"],
      bestseller: true,
      rating: 4.9,
      reviewsCount: 160,
      tags: ["photo cake", "custom", "birthday"],
      available: true
    },
    {
      id: "cake-013",
      name: "Designer Crown Birthday Cake",
      category: "cakes",
      subCategory: "Designer Cakes",
      price: 750,
      unit: "1.0 kg",
      isCake: true,
      description: "Royal 3D fondant crown cake with gold pearl sprinkles.",
      fullDesc: "Stunning celebration centerpiece decorated with a golden crown topper and fondant pearl lace.",
      image: "https://images.unsplash.com/photo-1578985545062-69928b1d9587?auto=format&fit=crop&w=800&q=80",
      ingredients: ["Fondant Crown", "Chocolate Sponge", "Gold Pearls"],
      bestseller: false,
      rating: 4.9,
      reviewsCount: 110,
      tags: ["designer", "crown", "gold"],
      available: true
    },
    {
      id: "cake-014",
      name: "Superhero Theme Kids Cake",
      category: "cakes",
      subCategory: "Kids Cakes",
      price: 699,
      unit: "1.0 kg",
      isCake: true,
      description: "Vibrant superhero theme cake customized for kids' birthday parties.",
      fullDesc: "Colorful birthday cake topped with edible 3D superhero emblems and vibrant butter icing.",
      image: "https://images.unsplash.com/photo-1565958011703-44f9829ba187?auto=format&fit=crop&w=800&q=80",
      ingredients: ["Vanilla Sponge", "Color Frosting", "Superhero Emblem"],
      bestseller: false,
      rating: 4.8,
      reviewsCount: 85,
      tags: ["kids", "superhero", "birthday"],
      available: true
    },
    {
      id: "cake-015",
      name: "Anniversary Rose Cascade Cake",
      category: "cakes",
      subCategory: "Anniversary Cakes",
      price: 799,
      unit: "1.0 kg",
      isCake: true,
      description: "Elegant 2-tier wedding anniversary cake with cascading fondant roses.",
      fullDesc: "Romantic celebration cake featuring hand-sculpted pink fondant roses cascading down ivory buttercream.",
      image: "https://images.unsplash.com/photo-1586985289688-ca3cf47d3e6e?auto=format&fit=crop&w=800&q=80",
      ingredients: ["Fondant Roses", "Red Velvet Sponge", "Cream Cheese"],
      bestseller: false,
      rating: 4.9,
      reviewsCount: 94,
      tags: ["anniversary", "rose", "wedding"],
      available: true
    },
    {
      id: "cake-016",
      name: "100% Eggless Chocolate Truffle",
      category: "cakes",
      subCategory: "Eggless Cakes",
      price: 510,
      unit: "0.5 kg",
      isCake: true,
      description: "100% pure veg dark chocolate truffle cake with rich ganache.",
      fullDesc: "Pure vegetarian chocolate sponge glazed in shiny dark chocolate ganache and chocolate ribbons.",
      image: "https://images.unsplash.com/photo-1578985545062-69928b1d9587?auto=format&fit=crop&w=800&q=80",
      ingredients: ["Eggless Cocoa Sponge", "Dark Ganache"],
      bestseller: true,
      rating: 4.9,
      reviewsCount: 175,
      tags: ["eggless", "truffle", "veg"],
      available: true
    },

    // ==========================================
    // BAKERY & SNACKS CATALOG (20+ Products)
    // ==========================================
    {
      id: "bakery-001",
      name: "Artisanal Whole Wheat Bread",
      category: "breads",
      subCategory: "Breads",
      price: 40,
      unit: "400g Loaf",
      isCake: false,
      description: "Daily baked 100% whole wheat bread loaf, zero preservatives.",
      fullDesc: "Freshly sliced artisan loaf prepared with stone-ground whole wheat flour, honey, and natural sourdough starter.",
      image: "https://images.unsplash.com/photo-1509440159596-0249088772ff?auto=format&fit=crop&w=800&q=80",
      ingredients: ["Whole Wheat", "Honey", "Yeast", "Sea Salt"],
      bestseller: true,
      rating: 4.8,
      reviewsCount: 310,
      tags: ["bread", "wheat", "healthy"],
      available: true
    },
    {
      id: "bakery-002",
      name: "Fresh Milk Sandwich Bread",
      category: "breads",
      subCategory: "Breads",
      price: 35,
      unit: "400g Loaf",
      isCake: false,
      description: "Soft white milk bread sliced for perfect breakfast sandwiches.",
      fullDesc: "Super soft sliced white loaf enriched with fresh dairy milk and pure butter.",
      image: "https://images.unsplash.com/photo-1509440159596-0249088772ff?auto=format&fit=crop&w=800&q=80",
      ingredients: ["Wheat Flour", "Fresh Milk", "Butter"],
      bestseller: true,
      rating: 4.7,
      reviewsCount: 260,
      tags: ["milk bread", "sandwich"],
      available: true
    },
    {
      id: "bakery-003",
      name: "Sweet Fruit Buns (Pack of 4)",
      category: "breads",
      subCategory: "Buns",
      price: 25,
      unit: "Pack of 4",
      isCake: false,
      description: "Soft fluffy buns filled with sweet tutti-frutti candied papaya bits.",
      fullDesc: "Traditional bakery buns studded with colorful candied fruits, perfect for tea dipping.",
      image: "https://images.unsplash.com/photo-1509440159596-0249088772ff?auto=format&fit=crop&w=800&q=80",
      ingredients: ["Flour", "Tutti Frutti", "Butter"],
      bestseller: false,
      rating: 4.6,
      reviewsCount: 140,
      tags: ["bun", "sweet bun", "fruit"],
      available: true
    },
    {
      id: "bakery-004",
      name: "Crispy Veg Potato Puff",
      category: "snacks",
      subCategory: "Puffs",
      price: 25,
      unit: "Per Piece",
      isCake: false,
      description: "Flaky golden puff pastry stuffed with spiced potato and pea filling.",
      fullDesc: "Flaky layers of golden baked pastry filled with Indian spiced potato masala, onions, and green coriander.",
      image: "https://images.unsplash.com/photo-1549931319-a545dcf3bc73?auto=format&fit=crop&w=800&q=80",
      ingredients: ["Puff Pastry", "Spiced Potato", "Peas"],
      bestseller: true,
      rating: 4.8,
      reviewsCount: 290,
      tags: ["veg puff", "puff", "snack"],
      available: true
    },
    {
      id: "bakery-005",
      name: "Paneer Butter Masala Puff",
      category: "snacks",
      subCategory: "Puffs",
      price: 35,
      unit: "Per Piece",
      isCake: false,
      description: "Golden flaky puff filled with cottage cheese cubes in rich tomato gravy.",
      fullDesc: "Puff pastry stuffed with soft paneer cubes cooked in rich butter masala sauce.",
      image: "https://images.unsplash.com/photo-1549931319-a545dcf3bc73?auto=format&fit=crop&w=800&q=80",
      ingredients: ["Paneer", "Puff Pastry", "Butter Masala"],
      bestseller: true,
      rating: 4.9,
      reviewsCount: 230,
      tags: ["paneer puff", "snack"],
      available: true
    },
    {
      id: "bakery-006",
      name: "Royal Bakery Butter Cookies",
      category: "cookies",
      subCategory: "Cookies",
      price: 200,
      unit: "1 kg Pack",
      isCake: false,
      description: "Melt-in-your-mouth Danish style golden butter cookies.",
      fullDesc: "Baked using 100% pure dairy butter and unbleached flour. Crispy, golden, and rich in natural butter aroma.",
      image: "https://images.unsplash.com/photo-1558961363-fa8fdf82db35?auto=format&fit=crop&w=800&q=80",
      ingredients: ["Pure Dairy Butter", "Cane Sugar", "Flour"],
      bestseller: true,
      rating: 4.9,
      reviewsCount: 215,
      tags: ["cookies", "butter", "biscuits"],
      available: true
    },
    {
      id: "bakery-007",
      name: "Crispy Almond Rusk",
      category: "cookies",
      subCategory: "Rusk",
      price: 90,
      unit: "400g Pack",
      isCake: false,
      description: "Double-baked crispy tea toast rusk topped with crushed almonds.",
      fullDesc: "Crunchy double-baked wheat toast biscuits infused with cardamom and sliced almonds.",
      image: "https://images.unsplash.com/photo-1558961363-fa8fdf82db35?auto=format&fit=crop&w=800&q=80",
      ingredients: ["Wheat Toast", "Almonds", "Cardamom"],
      bestseller: false,
      rating: 4.7,
      reviewsCount: 165,
      tags: ["rusk", "tea toast"],
      available: true
    },
    {
      id: "bakery-008",
      name: "Chocolate Glazed Donut",
      category: "pastries",
      subCategory: "Donuts",
      price: 60,
      unit: "Per Piece",
      isCake: false,
      description: "Soft ring donut dipped in dark chocolate glaze and sprinkles.",
      fullDesc: "Airy yeast-risen donut dipped in warm dark chocolate glaze and colorful sprinkles.",
      image: "https://images.unsplash.com/photo-1551024709-8f23befc6f87?auto=format&fit=crop&w=800&q=80",
      ingredients: ["Yeast Dough", "Chocolate Glaze", "Sprinkles"],
      bestseller: true,
      rating: 4.8,
      reviewsCount: 180,
      tags: ["donut", "chocolate"],
      available: true
    },

    // ==========================================
    // COOL DRINKS & BEVERAGES CATALOG (20+ Products)
    // ==========================================
    {
      id: "drink-001",
      name: "Chilled Saffron Badam Milk",
      category: "drinks",
      subCategory: "Milk Drinks",
      price: 60,
      unit: "300ml Bottle",
      isCake: false,
      description: "Traditional almond milk infused with saffron, cardamom and silvered nuts.",
      fullDesc: "Slow-cooked full cream milk blended with roasted California almonds, Kashmir saffron, green cardamom, and served ice-cold in glass bottles.",
      image: "https://images.unsplash.com/photo-1556881286-fc6915169721?auto=format&fit=crop&w=800&q=80",
      ingredients: ["Pure Milk", "Roasted Almonds", "Kashmir Saffron"],
      bestseller: true,
      rating: 4.9,
      reviewsCount: 220,
      tags: ["badam milk", "saffron", "cool drink"],
      available: true
    },
    {
      id: "drink-002",
      name: "Special Chilled Rose Milk",
      category: "drinks",
      subCategory: "Milk Drinks",
      price: 50,
      unit: "300ml Bottle",
      isCake: false,
      description: "Refreshing cold milk blended with fragrant organic rose syrup and sabja seeds.",
      fullDesc: "Fresh cold milk infused with aromatic rose petal extract, natural cane sugar, and cooling basil seeds.",
      image: "https://images.unsplash.com/photo-1541658016709-82535e94bc69?auto=format&fit=crop&w=800&q=80",
      ingredients: ["Fresh Milk", "Organic Rose Syrup", "Sabja Seeds"],
      bestseller: true,
      rating: 4.8,
      reviewsCount: 195,
      tags: ["rose milk", "cool drink"],
      available: true
    },
    {
      id: "drink-003",
      name: "Cold Coffee with Vanilla Scoop",
      category: "drinks",
      subCategory: "Coffee & Shakes",
      price: 90,
      unit: "350ml Glass",
      isCake: false,
      description: "Thick espresso cold coffee topped with a scoop of vanilla ice cream & chocolate drizzle.",
      fullDesc: "Freshly brewed espresso blended with cold milk and chocolate syrup, served thick with vanilla ice cream.",
      image: "https://images.unsplash.com/photo-1517701604599-bb29b565090c?auto=format&fit=crop&w=800&q=80",
      ingredients: ["Espresso Coffee", "Chilled Milk", "Vanilla Ice Cream"],
      bestseller: true,
      rating: 4.9,
      reviewsCount: 240,
      tags: ["cold coffee", "ice cream", "shake"],
      available: true
    },
    {
      id: "drink-004",
      name: "Fresh Alphonso Mango Lassi",
      category: "drinks",
      subCategory: "Smoothies",
      price: 70,
      unit: "300ml Glass",
      isCake: false,
      description: "Thick sweet curd smoothie blended with natural Alphonso mango pulp.",
      fullDesc: "Creamy curd whipped smooth with Alphonso mango puree, topped with pistachios and saffron.",
      image: "https://images.unsplash.com/photo-1546173159-315724a31696?auto=format&fit=crop&w=800&q=80",
      ingredients: ["Sweet Curd", "Alphonso Mango Pulp", "Pistachios"],
      bestseller: false,
      rating: 4.8,
      reviewsCount: 130,
      tags: ["mango lassi", "smoothie"],
      available: true
    },
    {
      id: "drink-005",
      name: "Coca-Cola Original (500ml)",
      category: "drinks",
      subCategory: "Sodas",
      price: 40,
      unit: "500ml Bottle",
      isCake: false,
      description: "Ice-cold refreshing Coca-Cola carbonated soft drink.",
      fullDesc: "Chilled 500ml pet bottle of original refreshing Coca-Cola.",
      image: "https://images.unsplash.com/photo-1622483767028-3f66f32aef97?auto=format&fit=crop&w=800&q=80",
      ingredients: ["Carbonated Water", "Sugar", "Cola Flavor"],
      bestseller: true,
      rating: 4.8,
      reviewsCount: 310,
      tags: ["coca cola", "coke", "soda"],
      available: true
    },
    {
      id: "drink-006",
      name: "Thums Up Charged (500ml)",
      category: "drinks",
      subCategory: "Sodas",
      price: 40,
      unit: "500ml Bottle",
      isCake: false,
      description: "Strong fizzy Indian cola with fizzy carbonation.",
      fullDesc: "Chilled 500ml bottle of spicy and strong Thums Up cola.",
      image: "https://images.unsplash.com/photo-1622483767028-3f66f32aef97?auto=format&fit=crop&w=800&q=80",
      ingredients: ["Carbonated Water", "Fizzy Cola Flavor"],
      bestseller: true,
      rating: 4.9,
      reviewsCount: 280,
      tags: ["thums up", "soda"],
      available: true
    },
    {
      id: "drink-007",
      name: "Sprite Lemon-Lime (500ml)",
      category: "drinks",
      subCategory: "Sodas",
      price: 40,
      unit: "500ml Bottle",
      isCake: false,
      description: "Clear crisp lemon-lime sparkling soda.",
      fullDesc: "Chilled 500ml bottle of clear, crisp Sprite lemon-lime soda.",
      image: "https://images.unsplash.com/photo-1622483767028-3f66f32aef97?auto=format&fit=crop&w=800&q=80",
      ingredients: ["Carbonated Water", "Lemon Lime Flavor"],
      bestseller: false,
      rating: 4.7,
      reviewsCount: 190,
      tags: ["sprite", "soda", "lime"],
      available: true
    },
    {
      id: "drink-008",
      name: "Red Bull Energy Drink",
      category: "drinks",
      subCategory: "Energy Drinks",
      price: 125,
      unit: "250ml Can",
      isCake: false,
      description: "Chilled Red Bull energy drink can with taurine & B-vitamins.",
      fullDesc: "Chilled 250ml can of Red Bull vitalizing energy drink.",
      image: "https://images.unsplash.com/photo-1622483767028-3f66f32aef97?auto=format&fit=crop&w=800&q=80",
      ingredients: ["Caffeine", "Taurine", "B-Vitamins"],
      bestseller: false,
      rating: 4.8,
      reviewsCount: 150,
      tags: ["red bull", "energy drink"],
      available: true
    }
  ];

  function getAllProducts() {
    return products;
  }

  function getProductById(id) {
    return products.find(p => p.id === id);
  }

  function filterProducts(category = 'all', searchQuery = '', sortOption = 'popular') {
    let list = [...products];

    if (category !== 'all') {
      list = list.filter(p => p.category === category);
    }

    if (searchQuery.trim() !== '') {
      const q = searchQuery.toLowerCase();
      list = list.filter(p => p.name.toLowerCase().includes(q) || p.description.toLowerCase().includes(q) || p.category.toLowerCase().includes(q) || (p.tags && p.tags.some(t => t.includes(q))));
    }

    if (sortOption === 'low-high') {
      list.sort((a, b) => a.price - b.price);
    } else if (sortOption === 'high-low') {
      list.sort((a, b) => b.price - a.price);
    } else if (sortOption === 'popular') {
      list.sort((a, b) => b.reviewsCount - a.reviewsCount);
    }

    return list;
  }

  return {
    getAllProducts,
    getProductById,
    filterProducts
  };
})();
